name       : mate-netbook
version    : 1.20.1
release    : 1
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-netbook-1.20.1.tar.xz : 58331b140c7b2c38edba9ab200aebd2e3a4655fbc65ff1df4ce748b315059ac6
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : A simple window management tool
description: |
    A simple window management tool which:
    * Allows you to set basic rules for a window type, such as maximise/undecorate.
    * Allows exceptions to the rules, based on string matching for window name and window class.
    * Allows 'reversing' of rules when the user manually changes something:
    * Re-decorates windows on un-maximise.
builddeps  :
    - pkgconfig(libfakekey)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(xtst)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
