name       : mate-netbook
version    : 1.22.2
release    : 4
source     :
    - https://github.com/mate-desktop/mate-netbook/archive/v1.22.2.tar.gz : bbadde2015e4e7dd537f8c1ff2a96dbe0997318b4594be3c61245fec6ce10296
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : A simple window management tool
description: |
    A simple window management tool which:
    * Allows you to set basic rules for a window type, such as maximise/undecorate.
    * Allows exceptions to the rules, based on string matching for window name and window class.
    * Allows 'reversing' of rules when the user manually changes something:
    * Re-decorates windows on un-maximise.
builddeps  :
    - pkgconfig(libfakekey)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(xtst)
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
