name       : mate-netbook
version    : 1.22.0
release    : 2
source     :
    - https://github.com/mate-desktop//mate-netbook/archive/v1.22.0.tar.gz : 0d620677fb78c311ea6bcfc5d6d9dfbbcaf297e09ae3e420e50bde614489800a
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : A simple window management tool
description: |
    A simple window management tool which:
    * Allows you to set basic rules for a window type, such as maximise/undecorate.
    * Allows exceptions to the rules, based on string matching for window name and window class.
    * Allows 'reversing' of rules when the user manually changes something:
    * Re-decorates windows on un-maximise.
builddeps  :
    - pkgconfig(libfakekey)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(xtst)
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
