name       : mate-netbook
version    : 1.27.0
release    : 7
source     :
    - https://github.com/mate-desktop/mate-netbook/releases/download/v1.27.0/mate-netbook-1.27.0.tar.xz : b41a890c515e4dc2f51038fbc0fca65344a3b8551c7d7fd04b5470f18049df4c
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : A simple window management tool
description: |
    A simple window management tool which:
    * Allows you to set basic rules for a window type, such as maximise/undecorate.
    * Allows exceptions to the rules, based on string matching for window name and window class.
    * Allows 'reversing' of rules when the user manually changes something:
    * Re-decorates windows on un-maximise.
builddeps  :
    - pkgconfig(libfakekey)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(xtst)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
